version: "3.3"
services:
  node1:
    image: yaml-metrics-demo
    build: .
  node2:
    image: yaml-metrics-demo
    depends_on:
      - node1
  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node1
      - node2
